changed port page
InternalDeveloperPlatform/public-site pull request #120
Opened 2023-06-14 08:22 UTC by EllaFurman

Updated port.md

2023-06-14 08:46 UTC, EllaFurman commented
Done :)

Ella Furman

Marketing Manager

Website - getport.io

Checkout our DevEx Community
<https://join.slack.com/t/devex-community/shared_invite/zt-1ksuwt1ir-7QkIIe5Ue3PXdun9YUWo3w>

Sent via Superhuman ***@***.***>


On Wed, Jun 14, 2023 at 11:32 AM, Florian Lipp ***@***.***>
wrote:

> @EllaFurman <https://github.com/EllaFurman> thanks for contributing.
> Could you please stick to the structure of the existing table and not
> replace it entirely? Thanks
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/InternalDeveloperPlatform/public-site/pull/120#issuecomment-1590728776>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2ZOI4EFMSGH2HHVMSJXB5DXLFZIJANCNFSM6AAAAAAZF7OBUY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-14 09:03 UTC, FL303 approved these changes

2023-06-14 11:22 UTC, christophcrichter commented on content/ecosystem/platform-tooling/developer-portals/port.md
> -+++
Please add this part back in. This is needed for general navigation. Thanks.

2023-06-14 11:22 UTC, christophcrichter requested changes
Please see my comment regarding the header.

2023-06-14 11:54 UTC, EllaFurman commented
Done :)

Ella Furman

Marketing Manager

Website - getport.io

Checkout our DevEx Community
<https://join.slack.com/t/devex-community/shared_invite/zt-1ksuwt1ir-7QkIIe5Ue3PXdun9YUWo3w>

Sent via Superhuman ***@***.***>


On Wed, Jun 14, 2023 at 2:22 PM, Christoph C. Richter <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please see my comment regarding the header.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/InternalDeveloperPlatform/public-site/pull/120#pullrequestreview-1479151831>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2ZOI4GUWSJU6WV7VVNMEF3XLGNIVANCNFSM6AAAAAAZF7OBUY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-06-14 19:56 UTC, christophcrichter approved these changes
LGTM; thanks for contributing

2023-06-14 19:56 UTC, merged

2023-06-19 08:52 UTC, EllaFurman commented
Thank you!
I put in another addition now :)

Ella Furman

Marketing Manager

getport.io

Join our Port Community
<https://join.slack.com/t/port-community/shared_invite/zt-1wdjwizkn-0i7g9LQeQ4rdU5_YSe6vDA>


Sent via Superhuman ***@***.***>


On Wed, Jun 14, 2023 at 10:56 PM, Christoph C. Richter <
***@***.***> wrote:

> Merged #120
> <https://github.com/InternalDeveloperPlatform/public-site/pull/120> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/InternalDeveloperPlatform/public-site/pull/120#event-9532735821>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2ZOI4E5OFBE4ROP2CFQGDLXLIJQXANCNFSM6AAAAAAZF7OBUY>
> .
> You are receiving this because you were mentioned.Message ID:
> <InternalDeveloperPlatform/public-site/pull/120/issue_event/9532735821@
> github.com>
>